// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTwYU7FYF4o94dpH_iWS2M_vzy7JoHhFE',
    appId: '1:49273305032:web:58ab8aecd50c50fe6ef2fd',
    messagingSenderId: '49273305032',
    projectId: 'video-editer-df6c2',
    authDomain: 'video-editer-df6c2.firebaseapp.com',
    storageBucket: 'video-editer-df6c2.appspot.com',
    measurementId: 'G-7QESKGF6FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZrzSGitGuaZ8Y74ba3QmgDhMOIjWg0rg',
    appId: '1:49273305032:android:853c97706b7299a36ef2fd',
    messagingSenderId: '49273305032',
    projectId: 'video-editer-df6c2',
    storageBucket: 'video-editer-df6c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJMqHtjZQ0X-naZQmtm0B9eDyXO9L3Rgs',
    appId: '1:49273305032:ios:43f8f0e85d9632dc6ef2fd',
    messagingSenderId: '49273305032',
    projectId: 'video-editer-df6c2',
    storageBucket: 'video-editer-df6c2.appspot.com',
    iosClientId: '49273305032-e32u8mosbomb9b44i45ln19bhptkhbl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoedit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJMqHtjZQ0X-naZQmtm0B9eDyXO9L3Rgs',
    appId: '1:49273305032:ios:6c8043f1ea1b018f6ef2fd',
    messagingSenderId: '49273305032',
    projectId: 'video-editer-df6c2',
    storageBucket: 'video-editer-df6c2.appspot.com',
    iosClientId: '49273305032-lanse9f2nl65mfak1km0hgt87gg61eq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoedit.RunnerTests',
  );
}
